apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL database
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - database
  - postgres
home: https://github.com/Ahmed7amed1/helm_chart_code_challenge
maintainers:
  - name: Ahmed Hamed
    url: https://github.com/Ahmed7amed1
